/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Generate the posts manifest and copy Markdown files.
 *
 * Returns the manifest JSON string (array of `PostMetadata`).
 */
export declare function generatePostsData(postsDir: string, outputDir: string, configJson: string): string
/**
 * Generate only the posts manifest without copying Markdown files.
 *
 * Use this for dev mode where files are served directly from source.
 * Returns the manifest JSON string (array of `PostMetadata`).
 */
export declare function generatePostsManifestOnly(postsDir: string, outputDir: string, configJson: string): string
/**
 * Generate album index and per-album detail JSON files, including
 * thumbnail generation and EXIF extraction.
 *
 * Returns the albums-index JSON string.
 */
export declare function generateAlbumsData(albumsDir: string, outputDir: string, albumConfigJson: string, siteConfigJson: string): string
/**
 * Generate SEO HTML pages for every post in the manifest.
 *
 * Returns the number of pages generated.
 */
export declare function generateSeoPages(manifestJson: string, templatePath: string, outputDir: string, configJson: string): number
/** Generate `sitemap.xml`. */
export declare function generateSitemap(manifestJson: string, outputPath: string, configJson: string): void
/** Generate `rss.xml`. */
export declare function generateRss(manifestJson: string, outputPath: string, configJson: string, postsDir?: string | undefined | null): void
/** Generate `robots.txt`. */
export declare function generateRobots(outputPath: string, configJson: string): void
/**
 * Execute the full production build pipeline.
 *
 * Accepts a JSON string of `BuildOptions`, returns a JSON string of `BuildResult`.
 */
export declare function buildCommand(optionsJson: string): string
/**
 * Start the development preview server and block until Ctrl+C.
 *
 * Accepts a JSON string of `ServeOptions`. Prints the server address to stdout,
 * then blocks until the process receives a termination signal.
 */
export declare function serveCommand(optionsJson: string): void
/** Update Spage core/plugin declarations and warm the package cache. */
export declare function updateResourcesCommand(optionsJson: string): string
/**
 * Sync local album media to S3-compatible storage.
 *
 * Accepts a JSON string of `SyncOptions`, returns a JSON string of `SyncResult`.
 * Prints progress to stdout for CLI usage.
 */
export declare function syncMediaCommand(optionsJson: string): string
/**
 * Sync media with a JS progress callback. Designed for Tauri/GUI integration.
 * Runs on a background thread (libuv thread pool), does NOT block the JS event loop.
 *
 * The callback receives a JSON string for each progress event:
 * `{"type":"generating_thumbnail","current":1,"total":44,"file":"album/photo.jpg"}`
 * `{"type":"uploading_thumbnail","current":1,"total":44}`
 * `{"type":"uploading","current":1,"total":11,"file":"album/photo.jpg"}`
 * `{"type":"scanning","total":11}`
 * `{"type":"done"}`
 *
 * Returns a Promise that resolves to the result JSON string.
 */
export declare function syncMediaWithProgress(optionsJson: string, callback: (arg: string) => any): Promise<unknown>
