/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsScaffoldInput {
  targetDir: string
  name: string
  description: string
  author: string
  siteUrl?: string
  timezone?: string
}
export declare function scaffoldBlog(input: JsScaffoldInput): void
export declare function cleanupBlog(targetDir: string): void
